name: Update profile statistics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&disable_animations=true&hide_title=true&border_radius=20&border_color=0d1117&bg_color=151b23&hide=contribs&text_color=e4e4e4&icon_color=ffffff&ring_color=ffffff&include_all_commits=true
          path: stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stats.svg
          git commit -m "Update profile statistics" || exit 0
          git push
